### ISSUE TITLE
Crash after taking photo in horizontal orientation

### ISSUE THREAD

**Issue by AlexX333BY** [AlexX333BY/lucky-mushroom-android#8]
After taking photo in horizontal orientation and pressing "Apply" button, UninitializedPropertyAccessException is thrown at line MainActivity.kt:50

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: by.bsuir.luckymushroom, PID: 26892
    java.lang.RuntimeException: Unable to resume activity {by.bsuir.luckymushroom/by.bsuir.luckymushroom.app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {by.bsuir.luckymushroom/by.bsuir.luckymushroom.app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property photoURI has not been initialized
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3785)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {by.bsuir.luckymushroom/by.bsuir.luckymushroom.app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property photoURI has not been initialized
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4361)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3774)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property photoURI has not been initialized
        at by.bsuir.luckymushroom.app.MainActivity.onActivityResult(MainActivity.kt:50)
        at android.app.Activity.dispatchActivityResult(Activity.java:7454)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4354)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3774) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

https://github.com/AlexX333BY/lucky-mushroom-android/blob/e226869b3fad8dad4ba3797f295d406911c52bff/app/src/main/java/by/bsuir/luckymushroom/app/MainActivity.kt#L50

**Comment by AlexX333BY** [comment]
Fixed with https://github.com/AlexX333BY/lucky-mushroom-android/pull/14
